/* eslint-disable no-unused-vars */
export enum Entity {
  USERS = 'USERS',
  TEACHERS = 'TEACHERS',
  COURSES = 'COURSES',
  EXAMS = 'EXAMS',
  ATTENDANCE = 'ATTENDANCE',
  LESSONS_PAPER = 'LESSONS_PAPER',
  LESSONS_VIDEO = 'LESSONS_VIDEO', // used by BE
  LESSONS_LIVE = 'LESSONS_LIVE', // used by BE
  SUBJECTS = 'SUBJECTS',
  PAYMENTS_STUDENTS = 'PAYMENTS', // used by BE
  LOGS = 'LOGS',
  STUDENT_INFO = 'STUDENT_INFO', // used by BE
  ACCESS_CODES = 'ACCESS_CODES',
  GIVEN_ACCESS_CODES = 'GIVEN_ACCESS_CODES',
  REPORTS = 'REPORTS'
}
